# Generated by Django 3.2.7 on 2021-12-13 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_auto_20211211_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='addressable_type',
            new_name='addressable_type',
        ),
        migrations.AlterField(
            model_name='employees',
            name='avatar',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='employees',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hrms.departments'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='directorate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hrms.directorates'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='nationality',
            field=models.CharField(choices=[('Uganda', 'Uganda'), ('Kenya', 'Kenya'), ('Rwanda', 'Rwanda'), ('South Sudan', 'South Sudan'), ('Burundi', 'Burundi'), ('Tanzania', 'tanzania'), ('Non EAC Country', 'Non EAC Country')], default='Uganda', max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='nin',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='nssf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='passport',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='permit',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='tin',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
