# Generated by Django 3.2.7 on 2021-12-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_rename_addressable_type_addresses_addressable_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='directorate_id',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='division_id',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='section_id',
        ),
    ]
