# Generated by Django 3.2.7 on 2021-12-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0009_rename_designation_id_employees_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designations',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='designations',
            old_name='directorate_id',
            new_name='directorate',
        ),
        migrations.RenameField(
            model_name='designations',
            old_name='division_id',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='designations',
            old_name='headed_entity_id',
            new_name='headed_entity',
        ),
        migrations.RenameField(
            model_name='designations',
            old_name='salary_scale_id',
            new_name='salary_scale',
        ),
        migrations.RenameField(
            model_name='designations',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='designations',
            old_name='supervisor_id',
            new_name='supervisor',
        ),
    ]
