# Generated by Django 3.2.7 on 2021-12-14 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0011_auto_20211214_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSNEStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_sne_statuses',
            },
        ),
        migrations.RenameField(
            model_name='employmenttypes',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='employee_status',
        ),
        migrations.AddField(
            model_name='employmenttenure',
            name='code',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmenttypes',
            name='code',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='employment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.employmentstatuses'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.employmenttenure'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.employmenttypes'),
        ),
        migrations.AddField(
            model_name='employees',
            name='employee_sne_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.employeesnestatuses'),
        ),
    ]
