# Generated by Django 3.2.7 on 2021-12-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0013_auto_20211215_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designations',
            name='max_holders',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='designations',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
