# Generated by Django 3.2.7 on 2021-12-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0014_auto_20211215_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designations',
            name='supervisor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hrms.designations'),
        ),
    ]
