# Generated by Django 3.2.7 on 2021-12-15 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0015_alter_designations_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designations',
            name='supervisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hrms.designations'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salaryscales',
            name='created_by',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salaryscales',
            name='updated_by',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
