# Generated by Django 3.2.7 on 2021-12-15 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0016_auto_20211215_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designations',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hrms.departments'),
        ),
        migrations.AlterField(
            model_name='designations',
            name='directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hrms.directorates'),
        ),
        migrations.AlterField(
            model_name='designations',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hrms.divisions'),
        ),
        migrations.AlterField(
            model_name='designations',
            name='salary_scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hrms.salaryscales'),
        ),
        migrations.AlterField(
            model_name='designations',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hrms.sections'),
        ),
    ]
